github_token: 
slack_token:

github_url: http://code.corp.surveymonkey.com
organization: wufoo

# List the repositories to be watched by the bot. If none are given, bot will watch all repositories
repositories:
  # - wufoo

