github_token: 
slack_token:

repositories: 
  devmonkeys:
    - enterpriseweb

# Restrict notifications to only be given to these users, or leave empty to notify any users
whitelist:

# Prevent these users from being messaged. Overrides whitelist
blacklist:


manually_resolve_users: