{name}Repo:repository(owner: "{org}", name: "{repo}") {{
  pullRequests(last: 100, states: OPEN) {{
    nodes {{
      number
      title
      url
      author {{
        ... on User {{
          login
          name
          email
        }}
        ... on Actor {{
          login
        }}
      }}
      assignees(first: 100) {{
        nodes {{
          login
          name
          email
        }}
      }}
      reviewRequests(first: 100) {{
        nodes {{
          requestedReviewer {{
            ... on User {{
              login
              name
              email
            }}
          }}
        }}
      }}
      reviews(last: 100, states: [CHANGES_REQUESTED, APPROVED]) {{
        nodes {{
          state
        }}
      }}
      branch:headRefName
    }}
  }}
}}
