# Entries are of the form
# Organization:
#   - Repository
# NOTE: THE MAXIMUM NUMBER OF REPOSITORIES THAT CAN BE QUERIED IS 70.
repositories:

# Restrict notifications to only be given to these Github users, or leave empty to notify any users
whitelist:

# Prevent these users from being messaged. Overrides whitelist
blacklist:

# For anyone whose Github username does not match their work email
manually_resolve_users:

use_jira: False

# Set this to 'True' if you would like to ignore no assigned users to a PR warnings
ignore_no_assigned: False

# Set this to 'True' if you would like to ignore no requested users to a PR warnings
ignore_no_requested: False
